### PR TITLE
feature: device add support unixsocket use fd

### PR DESCRIPTION
**Pull request by lflish**
This is a great project.
For ease of use, I gave it a little detail. 
Using FD is compatible with all Linux communication, and I optimized it to use Unix sockets directly，It has no effect on the original method

`
device: unix:///tmp/unix_socket
`

### CODE REVIEW

**Comment by xjasonlyu** [comment]
Hi! Thanks for your PR.

Unix socket can be a great source input for tun2socks project. Can we implement it in the `core/device` pkg directly?

**Comment by lflish** [comment]
你好
新改的代码放到了core/device目录了，但是对设备解析的函数`parseDevice`中， url.Parse(s)函数对`unix:///tmp/unix.sock`这种格式解析有问题，所以把这里也重新写了下。
```
	devInfo := strings.Split(s, "://")
	if len(devInfo) < 2 {
		return nil, fmt.Errorf("unsupported device: %s", s)
	}
	driver, name := devInfo[0], devInfo[1]
```

**Comment by xjasonlyu** [comment]
这个解析其实没有问题，你不用 `u.Host`，直接用 `u.Path` 就行了。

**Comment by lflish** [comment]
多谢指点，这块代码回滚重新提交了

**Pull request closed without merging**
