### PR TITLE
[WIP] Implement -remote-dns for HTTP and SOCKS5

### PR DESCRIPTION
**Pull request by blechschmidt**
Hello,

kudos for the great project. This is a superior replacement for the `badvpn` tool.

The motivation for this PR is the lack of UDP support by many proxies and the necessity to rely on third-party DNS resolvers even when UDP is supported. Thus, this PR implements an optional flag `-remote-dns` which enables the dialing of connections via DNS names instead of IP addresses.

This commit implements the ability to resolve IP addresses remotely via SOCKS5 or HTTP. It does so by intercepting DNS A and AAAA queries and replying with IP addresses from a virtual IP space which is reserved for DNS resolves. When an application performs a DNS lookup, a mapping from the virtual IP to a DNS name is created and cached for a short period of time. If the application subsequently connects to the virtual IP, the dialer will use the DNS name from the mapping instead of the destination IP address.

For short-time caching, [a modified version of go-cache](https://github.com/dossy/go-cache) is added as a new dependency. For DNS, [this DNS module](https://github.com/miekg/dns) is added.

### CODE REVIEW

**Comment by xjasonlyu** [comment]
Hi,

First of all, thank you for the excellent PR! The `-remote-dns` option you introduced is actually a feature we called [`fakedns`](https://github.com/xjasonlyu/tun2socks/tree/v1/component/fakedns) that was implemented in the previous major version, and we usually use `198.18.0.0/15` as the reserved IP subnet. Initially, I didn't plan to add this feature in current version since I believe it could be handled by another upstream proxy servers. But I'm open for PRs!

There are some implementations that may need further improvement:
- The [go-cache](https://github.com/dossy/go-cache) you're using seems to be outdated and lacking maintenance, so I don't think it's a good idea to use it directly. Switching to another in-memory cache might be better.
- The feature should work with any proxy protocols that support remote hostname resolving, e.g. socks4a/socks5/http/shadowsocks. So the PR shouldn't stick with HTTP and SOCKS5 only.
- Since it's only virtual IP addresses, it should be irrelevant with IPv4 or IPv6, all we need is hostname to IP mapping so that the tun2socks knows the domain the client is trying to send. Thus, I think virtual IP address in IPv4 is enough for this job, which is why the previous implementation of `fakedns` uses IPv4 only.

For some specific implements, code reviewing and response might be delayed since I've been busy lately.

**Comment by xjasonlyu** [comment]
There's another issue, the feature would fail if the last ip of reserved ip subnet has been used, which makes it not sustainable.

**Comment by blechschmidt** [comment]
> There's another issue, the feature would fail if the last ip of reserved ip subnet has been used, which makes it not sustainable.

I realized that a line got lost during refactoring locally. 2f006a5f73dd137fddd362d2d8ac5565510f33db causes the IP addresses to wrap around. The space can still be exhausted if you have more connections (actually active cache entries) than addresses inside the subnet, but this is just in the nature of this feature.

> The feature should work with any proxy protocols that support remote hostname resolving, e.g. socks4a/socks5/http/shadowsocks. So the PR shouldn't stick with HTTP and SOCKS5 only.

Implementing SOCKS4a and Shadowsocks came for free. I have tested it with a Shadowsocks server now. SOCKS4a looks good in Wireshark so far, but I still need to test it with a real server.

If you are, in principle, okay with this feature to be merged, I will still fix the other issues you mentioned and get back to you afterwards. I will also still change the caching behavior as it is currently not too smart to tell clients that a DNS response is to be cached for 60 seconds, while potentially dropping the mapping earlier. I will remove the manual purging and instead always update the cache TTL to at least the UDP timeout as soon as a packet belonging to the connection is observed.

**Comment by xjasonlyu** [comment]
> I realized that a line got lost during refactoring locally. 2f006a5 causes the IP addresses to wrap around. The space can still be exhausted if you have more connections (actually active cache entries) than addresses inside the subnet, but this is just in the nature of this feature.

Yes, but I mean it at least won't be exhausted if it just reached the end of the subnet lol.

> Implementing SOCKS4a and Shadowsocks came for free. 

Yep. And it's actually proxy-independent.

> I have tested it with a Shadowsocks server now. SOCKS4a looks good in Wireshark so far, but I still need to test it with a real server.

Shadowsocks is just kind of a revision of SOCKS5 with more features; But for SOCKS4A, it might have some issues: SOCKS4 doesn't support remote resolving but SOCKS4A does, but it's difficult to tell if the proxy server support 4A or not since they replied with the same version code.

> If you are, in principle, okay with this feature to be merged, I will still fix the other issues you mentioned and get back to you afterwards. I will also still change the caching behavior as it is currently not too smart to tell clients that a DNS response is to be cached for 60 seconds, while potentially dropping the mapping earlier. I will remove the manual purging and instead always update the cache TTL to at least the UDP timeout as soon as a packet belonging to the connection is observed.

I'm glad that you're trying to add this feature that I didn't get enough time to support it before. And of course I will merge this feature if it's well tested and fit the project. But it has a lot works to do (bug fixes, reviewing, code styles, other details and more) and I don't have enough time in the next months. So it may take longer than you thought to get it finally merged if you still want. And also, I'm inclined to implement it in a mature way like `fakedns` in [Clash](https://github.com/Dreamacro/clash), so even if you don't submit this PR, I will still transplant the fakedns to the project someday eventually.

**Comment by xjasonlyu** [comment]
@blechschmidt Hi, thank you for helping me improve this project, but maybe don’t rush to make changes. 

There’re some things we can discuss with, like the ttl cache. i’m thinking that use LRU cache might be a better solution, and this [guidance](https://manual.nssurge.com/book/understanding-surge/en/#virtual-nic-takeover-method-2) explains the TTL used in fake-ip that might be helpful.

**Comment by blechschmidt** [comment]
Sorry for the rush. I just realized that it was too early to submit the PR and wanted to fix things in a hurry. I realized that I had a misconception about how the connection tracking, in particular for UDP, worked.

Actually, I noticed that one only needs to cache the virtual IP to DNS name mapping for one or two seconds for the dialing to occur. Apart from that, there is no need to keep the items in the cache or even update their TTL. If I am not mistaken, this would allow for the recycling of IP virtual addresses, so one could, contrary to what I said above, have indeed more concurrent connections than addresses in the virtual IP space because the local endpoints are unique. All in all, this would mean that the cache only ever needs to hold maybe a handful of entries under normal operation.

So instead of abusing the cache as a kind of NAT table, which is what I had in mind initially, a better solution probably just provides the dialer with modified metadata, while leaving it in its original state everywhere else. In the current state of the PR, the problem is that the `PacketConn` handling UDP will get confused if the caching time does not exceed the UDP connection duration because the `remote` parameter passed to `handleUDPToRemote` is the DNS name first and later the virtual IP address.

**Comment by blechschmidt** [comment]
I will close this PR for now. It was too rushed and it has diverged too much from the main branch in the meanwhile. Nevertheless, I am still interested in having this functionality implemented.

**Pull request closed without merging**
