### PR TITLE
feat: add workflow to publish to winget

### PR DESCRIPTION
**Pull request by CoolPlayLin**
I am glad to see this perfect project. I've helped you publish this software winget. Now, you only need to do something easy, you could update it every you released.

Requirements
- Fork https://github.com/microsoft/winget-pkgs to your own account
- Add a token called `WINGET_TOKEN` with public repo permission to secrets
- https://github.com/microsoft/winget-pkgs/pull/117048 has been merged

### CODE REVIEW

**Comment by CoolPlayLin** [comment]
用户使用 WinGet 安装配置应该会比手动添加到系统变量方便不少

**Comment by xjasonlyu** [comment]
我觉得你可以单独开一个仓库上传到 winget，相当于第三方的支持也不错。

**Comment by CoolPlayLin** [comment]
第一发支持应该发布得更快

**Comment by xjasonlyu** [comment]
> 第一发支持应该发布得更快

是的，但是目前这个项目我倾向于仅在 GitHub 上提供。

**Pull request closed without merging**
